services:
  postgres:
    container_name: plant-nursery-container
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./src/main/resources/db/migration/V1.0__CreatingTable.sql:/docker-entrypoint-initdb.d/V1.0__CreatingTable.sql
    env_file:
      - .env
    ports:
      - 5433:5432

volumes:
  pgdata:
